# Generated by Django 4.2.5 on 2023-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-02-18'),
            preserve_default=False,
        ),
    ]
